; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ttgo-t-watch]
platform = espressif32
board = ttgo-t-watch
framework = arduino
; upload_port = /dev/ttyACM0 ; REPLACE THIS is you encounter any problems with port when uploading, specificly used for WSL USB connection
upload_port = COM5
lib_deps = 
	xinyuan-lilygo/TTGO TWatch Library@^1.4.2






; POWERSHELL:
; usbipd bind --busid 1-8
; usbipd attach --wsl --busid 1-8 

; WSL;
; ls /dev/tty